const listanombresmasculinos = [
    "Aaron", "Abel", "Abelardo", "Abraham", "Absalon", "Adalberto", "Adan", "Adolfo", "Adrian", "Adriano",
    "Agustin", "Albano", "Alberto", "Alejandro", "Alejo", "Alfonso", "Alfredo", "Alonso", "Alvaro", "Amadeo",
    "Amador", "Amalio", "Amando", "Ambrosio", "Amilcar", "Anacleto", "Anastasio", "Andres", "Angel", "Anibal",
    "Anselmo", "Antonio", "Aristoteles", "Armando", "Arquimedes", "Arturo", "Augusto", "Aurelio", "Avelino",
    "Balduino", "Baltasar", "Bartolome", "Basilio", "Bautista", "Beltran", "Benedicto", "Benicio", "Benigno",
    "Benito", "Benjamin", "Bernabe", "Bernardo", "Blas", "Bonifacio", "Braulio", "Bruno", "Buenaventura",
    "Cain", "Calixto", "Camilo", "Candido", "Carlos", "Carmelo", "Casimiro", "Casto", "Cayetano", "Ceferino",
    "Celestino", "Celso", "Cesar", "Ciceron", "Cipriano", "Cirilo", "Ciro", "Claudio", "Clemente", "Constantino",
    "Cornelio", "Cosme", "Cristian", "Cristobal", "Custodio", "Dalmiro", "Damaso", "Damian", "Daniel", "Dante",
    "Dario", "David", "Dedalo", "Demetrio", "Democrito", "Denis", "Desiderio", "Diego", "Dionisio", "Domiciano",
    "Domingo", "Edelmiro", "Edmundo", "Eduardo", "Efrain", "Efren", "Eleuterio", "Elias", "Eloy", "Emiliano",
    "Emilio", "Eneas", "Enrique", "Epicuro", "Epifanio", "Erasmo", "Ernesto", "Eros", "Espartaco", "Estanislao",
    "Esteban", "Eugenio", "Eulalio", "Eulogio", "Eusebio", "Eustaquio", "Eustasio", "Evaristo", "Ezequiel",
    "Fabian", "Fabio", "Fabricio", "Faustino", "Fausto", "Federico", "Feliciano", "Felipe", "Felix", "Fermin",
    "Fernan", "Fernando", "Fidel", "Filemon", "Filiberto", "Flavio", "Florencio", "Florian", "Fortunato",
    "Francisco", "Froilan", "Fructuoso", "Gabino", "Gabriel", "Gael", "Galileo", "Garcia", "Garcilaso", "Gaspar",
    "Gaston", "Gerardo", "German", "Gervasio", "Gilberto", "Goliat", "Gonzalo", "Gregorio", "Guillermo", "Gumersindo",
    "Gustavo", "Guzman", "Hector", "Heliodoro", "Heraclio", "Heraclito", "Heraldo", "Hercules", "Hermenegildo", "Hermes",
    "Herminio", "Hermogenes", "Hilario", "Hipolito", "Homero", "Horacio", "Hortensio", "Hugo", "Humberto", "Iago",
    "Icaro", "Ignacio", "Ildefonso", "Imanol", "Indalecio", "Inocencio", "Iñigo", "Isaac", "Isaias", "Isidoro",
    "Isidro", "Ismael", "Israel", "Ivan", "Jacinto", "Jason", "Javier", "Jesus", "Joaquin", "Jorge", "Jose",
    "Juan", "Laureano", "Lazaro", "Leandro", "Leocadio", "Leon", "Leonardo", "Leopoldo", "Liborio", "Lope", "Lorenzo",
    "Lucas", "Luciano", "Lucio", "Luis", "Macario", "Malaquias", "Manuel", "Marcelino", "Marcelo", "Marcial", "Marcio",
    "Marco", "Marcos", "Mariano", "Mario", "Martin", "Matias", "Mauricio", "Maximiliano", "Maximo", "Melchor", "Meliton",
    "Mercurio", "Miguel", "Modesto", "Moises", "Nabor", "Nabucodonosor", "Narciso", "Nazario", "Neftali", "Neptuno", "Neron",
    "Nestor", "Nicanor", "Nicasio", "Nicolas", "Noa", "Noe", "Octavio", "Oliver", "Oliverio", "Onesimo", "Onofre", "Orfeo",
    "Origenes", "Orion", "Orlando", "Oscar", "Osvaldo", "Otelo", "Ovidio", "Pablo", "Pancracio", "Pantaleon", "Pascual",
    "Pastor", "Patricio", "Pedro", "Pelayo", "Perfecto", "Pericles", "Perpetuo", "Perseo", "Pio", "Placido", "Poncio",
    "Prudencio", "Quiliano", "Quirino", "Rafael", "Raimundo", "Ramiro", "Ramon", "Raul", "Regino", "Renato", "Reyes",
    "Ricardo", "Roberto", "Rodolfo", "Rodrigo", "Rogelio", "Roman", "Roque", "Rufino", "Sabino", "Salomon", "Salvador",
    "Samuel", "Sancho", "Sanson", "Santiago", "Saturnino", "Saulo", "Sebastian", "Segismundo", "Serafin", "Sergio", "Servando",
    "Severo", "Silvano", "Silverio", "Silvestre", "Simeon", "Simon", "Sixto", "Tadeo", "Telmo", "Teo", "Teobaldo", "Teodorico",
    "Teodoro", "Teodosio", "Tico", "Timoteo", "Tirso", "Tomas", "Tristan", "Tulio", "Ubaldo", "Ulises", "Urbano", "Valentin",
    "Valeriano", "Valerio", "Venancio", "Ventura", "Vicente", "Victor", "Victoriano", "Victorio", "Virgilio", "Wenceslao",
    "Wilfredo", "Wilmer", "Xander", "Xavier", "Ximeno", "Yago", "Yahir", "Yeray", "Yuri", "Zacarias", "Zadkiel", "Zuriel",
];

const listanombresfemeninos = [
    "Abigail", "Abril", "Ada", "Adela", "Adelaida", "Adoracion", "Adriana", "Agata", "Agustina", "Aida",
    "Alba", "Alejandra", "Alexia", "Alfonsa", "Alicia", "Alma", "Amada", "Amalia", "Amanda", "Amapola",
    "Amaya", "Amelia", "America", "Amparo", "Ana", "Anastasia", "Andrea", "Andreyna", "Angela", "Angeles",
    "Antonia", "Antonieta", "Araceli", "Aranzazu", "Ariana", "Ascension", "Astrid", "Asuncion", "Aurelia",
    "Aurora", "Australia", "Azucena", "Azul", "Barbara", "Basilia", "Beatriz", "Begoña", "Belen", "Bella",
    "Bernarda", "Berta", "Betty", "Bianca", "Bibiana", "Brigida", "Brigitte", "Bruna", "Camila", "Candela",
    "Candelaria", "Candida", "Caridad", "Carla", "Carlota", "Carmela", "Carmen", "Carolina", "Catalina",
    "Cecilia", "Celeste", "Celestina", "Celia", "Cinthia", "Cintia", "Clara", "Claudia", "Cleopatra",
    "Concepcion", "Constanza", "Consuelo", "Cristina", "Dafne", "Dalia", "Dalila", "Damaris", "Dana",
    "Daniela", "Daria", "Debora", "Delfina", "Delia", "Demetria", "Desdemona", "Diana", "Dolores",
    "Dominique", "Dora", "Dulcinea", "Elena", "Elisa", "Elizabeth", "Eloisa", "Elsa", "Elvira", "Emilia",
    "Emiliana", "Emma", "Encarnacion", "Engracia", "Enriqueta", "Erika", "Ernestina", "Esmeralda",
    "Esperanza", "Estefania", "Estela", "Esther", "Estrella", "Eufemia", "Eugenia", "Eulalia", "Eva",
    "Fabiana", "Fabiola", "Fatima", "Faustina", "Fedora", "Fedra", "Felicia", "Felicidad", "Fernanda",
    "Flavia", "Flor", "Flora", "Florida", "Francisca", "Fuensanta", "Gabriela", "Gala", "Gema", "Genoveva",
    "Geraldina", "Gilberta", "Gina", "Gisela", "Gloria", "Gracia", "Graciela", "Griselda", "Guadalupe",
    "Guillermina", "Heidi", "Hermelinda", "Herminia", "Hilaria", "Himelda", "Hipolita", "Hortensia",
    "Ignacia", "Ileana", "Indira", "Ines", "Ingrid", "Inmaculada", "Irene", "Irene", "Irina", "Irma",
    "Isabella", "Isadora", "Isidora", "Isis", "Jacinta", "Janet", "Jazmin", "Jennifer", "Jesica",
    "Jimena", "Joaquina", "Josefa", "Josefina", "Jovita", "Juana", "Judith", "Julia", "Juliana", "Julieta",
    "Justa", "Justina", "Kalina", "Katia", "Laila", "Lara", "Laura", "Leandra", "Leonarda", "Leonor", "Leticia",
    "Lidia", "Lilia", "Lina", "Linda", "Lisa", "Liset", "Lola", "Lorena", "Lourdes", "Lucia", "Lucrecia", "Luisa",
    "Luna", "Luz", "Macarena", "Magdalena", "Maite", "Manuela", "Marcela", "Maria", "Mariana", "Marina", "Marta",
    "Maya", "Melisa", "Miriam", "Monica ", "Naiara", "Narcisa", "Natalia", "Natividad", "Nazaret", "Nelida", "Nieves",
    "Noa", "Noelia", "Noemi", "Nora", "Norma", "Nuria", "Nydia", "Obdulia", "Octavia", "Ofelia", "Olalla", "Olga",
    "Olimpia", "Oliva", "Olivia", "Ovidia", "Palmira", "Paloma", "Pandora", "Paola", "Patricia", "Paula", "Paulina",
    "Paz", "Penelope", "Perla", "Petra", "Pia", "Piedad", "Pilar", "Primitiva", "Prudencia", "Pura", "Purificacion",
    "Querida", "Quiana", "Raiza", "Ramona", "Raquel", "Rebeca", "Refugio", "Regina", "Remedios", "Renata", "Roberta",
    "Rocio", "Romina", "Rosa", "Rosalia", "Rosana", "Rosario", "Rosaura", "Roxana", "Ruth", "Sabina", "Sabrina",
    "Salma", "Salome", "Salvadora", "Sandra", "Sara", "Sibila", "Silvia", "Socorro", "Sofia", "Sol", "Soledad",
    "Sonia", "Soraya", "Stella", "Tabata", "Tamara", "Tania", "Tatiana", "Telma", "Teodora", "Teresa", "Tomasa",
    "Trinidad", "Ulalia", "Ursula", "Uxia", "Valentina", "Valeria", "Vanesa", "Veronica", "Veronica", "Victoria",
    "Violeta", "Virginia", "Wanda", "Xenia", "Ximena", "Xiomara", "Yaritza", "Yolanda", "Yuridia", "Yvonne",
    "Zaida", "Zaira", "Zara", "Zoraida", "Zulema"
];

const listaapellidos = [
    "Abeyta", "Abrego", "Abreu", "Acevedo", "Acosta", "Acuña", "Adame", "Adorno", "Agosto", "Aguayo",
    "Aguilar", "Aguilera", "Aguirre", "Alanis", "Alaniz", "Alarcon", "Alba", "Albornoz", "Alcala", "Alcantar",
    "Alcaraz", "Alejandro", "Aleman", "Alfaro", "Alicea", "Almanza", "Almaraz", "Almonte", "Alonso", "Alonzo",
    "Altamirano", "Alva", "Alvarado", "Alvarez", "Alvear", "Amador", "Amaya", "Amores", "Anaya", "Anguiano",
    "Angulo", "Aparicio", "Apodaca", "Aponte", "Aragon", "Aranda", "Araña", "Araujo", "Arce", "Archuleta",
    "Arellano", "Arenas", "Arevalo", "Arguello", "Arias", "Arizmendi", "Armas", "Armendariz", "Armenta", "Armijo",
    "Arredondo", "Arreola", "Arriaga", "Arroyo", "Arteaga", "Atencio", "Avalos", "Avila", "Aviles", "Ayala", "Baca",
    "Badillo", "Baez", "Baeza", "Bahena", "Balderas", "Ballesteros", "Banda", "Bañuelos", "Barajas", "Barela",
    "Barragan", "Barraza", "Barrera", "Barreto", "Barrientos", "Barrios", "Batista", "Becerra", "Beltran",
    "Benavides", "Benavidez", "Benitez", "Bermudez", "Bernal", "Berrios", "Betancourt", "Blanco", "Bonilla",
    "Borrego", "Botello", "Bravo", "Briones", "Briseño", "Brito", "Bueno", "Burgos", "Bustamante", "Bustos",
    "Caballero", "Caban", "Cabrera", "Cadena", "Caldera", "Calderon", "Calvillo", "Camacho", "Camarillo", "Campos",
    "Canales", "Candela", "Candelaria", "Cano", "Cantu", "Caraballo", "Carbajal", "Cardenas", "Cardona", "Carmona",
    "Carranza", "Carrasco", "Carrasquillo", "Carreon", "Carrera", "Carrero", "Carrillo", "Carrion", "Carvajal",
    "Casanova", "Casares", "Casarez", "Casas", "Casillas", "Castañeda", "Castellanos", "Castillo", "Castro",
    "Cavazos", "Cazares", "Ceballos", "Cedillo", "Ceja", "Centeno", "Cepeda", "Cerda", "Cervantes", "Cervantez",
    "Chacon", "Chapa", "Chavarria", "Chavez", "Cifuentes", "Cintron", "Cisneros", "Collado", "Collazo", "Colon",
    "Colunga", "Concepcion", "Contreras", "Cordero", "Cordova", "Cornejo", "Corona", "Coronado", "Corral",
    "Corrales", "Correa", "Cortes", "Cortez", "Corzo", "Cotto", "Covarrubias", "Crespo", "Cruz", "Cuellar",
    "Curiel", "Davila", "de Anda", "de Jesus", "Delacruz", "Delafuente", "Delagarza", "Delao", "Delapaz",
    "Delarosa", "Delatorre", "Deleon", "Delgadillo", "Delgado", "Delrio", "Delvalle", "Diaz", "Dominguez",
    "Dominquez", "Duarte", "Dueñas", "Duran", "Durand", "Echevarria", "Elizondo", "Enriquez", "Escalante",
    "Escamilla", "Escobar", "Escobedo", "Esparza", "Espinal", "Espino", "Espinosa", "Espinoza", "Esquibel", "Esquivel",
    "Estevez", "Estrada", "Fajardo", "Farias", "Feliciano", "Fernandez", "Ferrer", "Fierro", "Figueroa", "Flores",
    "Florez", "Fonseca", "Franco", "Frias", "Fuentes", "Furest", "Gaitan", "Galarza", "Galindo", "Gallardo", "Gallegos",
    "Galvan", "Galvez", "Gamboa", "Gamez", "Gaona", "Garay", "Garcia", "Garibay", "Garica", "Garrido", "Garza",
    "Gastelum", "Gaytan", "Gil", "Giraldo", "Giron", "Godinez", "Godoy", "Gomez", "Gonzales", "Gonzalez", "Gracia",
    "Granado", "Granados", "Griego", "Grijalva", "Guajardo", "Guardado", "Guerra", "Guerrero", "Guevara", "Guillen",
    "Gurule", "Gutierrez", "Guzman", "Haro", "Henriquez", "Heredia", "Hernadez", "Hernandes", "Hernandez", "Herrera",
    "Hidalgo", "Hinojosa", "Holguin", "Huerta", "Hurtado", "Ibañez", "Ibarra", "Iglesias", "Irizarry", "Jaime",
    "Jaimes", "Jaquez", "Jaramillo", "Jasso", "Jimenez", "Jiminez", "Juarez", "Jurado", "Laboy", "Lara", "Laureano",
    "Leal", "Lebron", "Ledesma", "Leiva", "Lemus", "Leon", "Lerma", "Leiva", "Lemus", "Leon", "Lerma", "Leyva", "Limon",
    "Linares", "Lira", "Llamas", "Llanos", "Loera", "Lomeli", "Longoria", "Lopez", "Lovato", "Loya", "Lozada", "Lozano",
    "Lucero", "Lucio", "Luevano", "Lugo", "Lujan", "Luna", "Macias", "Madera", "Madrid", "Madrigal", "Maestas", "Magaña",
    "Malave", "Maldonado", "Manzanares", "Maravilla", "Mares", "Marin", "Marquez", "Marrero", "Marroquin",
    "Martinez", "Mascareñas", "Mata", "Mateo", "Matias", "Matos", "Maya", "Mayorga", "Medina", "Medrano",
    "Mejia", "Melendez", "Melgar", "Mena", "Menchaca", "Mendez", "Mendoza", "Menendez", "Meraz", "Mercado",
    "Merino", "Mesa", "Meza", "Miramontes", "Miranda", "Mireles", "Mojica", "Molina", "Mondragon", "Monroy",
    "Montalvo", "Montañez", "Montaño", "Montemayor", "Montenegro", "Montero", "Montes", "Montez", "Montiel",
    "Montoya", "Mora", "Morales", "Moreno", "Mota", "Moya", "Munguia", "Muñiz", "Muñoz", "Murillo", "Muro",
    "Najera", "Naranjo", "Narvaez", "Nava", "Navarrete", "Navarro", "Nazario", "Negrete", "Negron", "Nevarez",
    "Nieto", "Nieves", "Niño", "Noguera", "Noriega", "Nuñez", "Ocampo", "Ocasio", "Ochoa", "Ojeda", "Olivares",
    "Olivarez", "Olivas", "Olivera", "Olivo", "Olmos", "Olvera", "Ontiveros", "Oquendo", "Ordoñez", "Orellana",
    "Ornelas", "Orosco", "Orozco", "Orta", "Ortega", "Ortiz", "Osorio", "Otero", "Ozuna", "Pabon", "Pacheco",
    "Padilla", "Padron", "Paez", "Pagan", "Palacios", "Palomares", "Palomino", "Palomo", "Pantoja", "Paredes",
    "Parra", "Partida", "Patiño", "Paz", "Pedraza", "Pedroza", "Pelayo", "Peña", "Perales", "Peralta", "Perea",
    "Peres", "Perez", "Pichardo", "Pineda", "Piña", "Pizarro", "Polanco", "Ponce", "Porras",
    "Portillo", "Posada", "Prado", "Preciado", "Prieto", "Puente", "Puga", "Pulido", "Quesada", "Quevedo", "Quezada",
    "Quintana", "Quintanilla", "Quintero", "Quiñones", "Quiñonez", "Quiroz", "Rael", "Ramirez", "Ramon", "Ramos",
    "Rangel", "Rascon", "Raya", "Razo", "Regalado", "Rendon", "Renteria", "Resendez", "Reyes", "Reyna", "Reynoso",
    "Rico", "Rincon", "Riojas", "Rios", "Rivas", "Rivera", "Rivero", "Robledo", "Robles", "Rocha", "Rodarte",
    "Rodrigez", "Rodriguez", "Rodriquez", "Rojas", "Rojo", "Roldan", "Rolon", "Roman", "Romero", "Romo", "Roque",
    "Rosado", "Rosales", "Rosario", "Rosas", "Roybal", "Rubio", "Ruelas", "Ruiz", "Ruvalcaba", "Saavedra", "Saenz",
    "Saiz", "Salas", "Salazar", "Salcedo", "Salcido", "Saldaña", "Saldivar", "Salgado", "Salinas", "Samaniego",
    "Sanches", "Sanchez", "Sandoval", "Santacruz", "Santana", "Santiago", "Santillan", "Sarabia", "Sarmiento",
    "Sauceda", "Saucedo", "Sedillo", "Segovia", "Segura", "Sepulveda", "Serna", "Serrano", "Serrato", "Sevilla",
    "Sierra", "Silva", "Sisneros", "Solano", "Solis", "Soliz", "Solorio", "Solorzano", "Soria", "Sosa", "Sotelo",
    "Soto", "Suarez", "Tafoya", "Tamayo", "Tamez", "Tapia", "Tejada", "Tejeda", "Tellez", "Tello", "Teran", "Terrazas",
    "Tijerina", "Tirado", "Toledo", "Toro", "Torres", "Torrez", "Tovar", "Trejo", "Treviño", "Trujillo", "Ulibarri",
    "Ulloa", "Urbina", "Ureña", "Urias", "Uribe", "Urrutia", "Vaca", "Valadez", "Valdes", "Valdez", "Valdivia",
    "Valencia", "Valentin", "Valenzuela", "Valladares", "Valle", "Vallejo", "Valles", "Valverde", "Vanegas",
    "Varela", "Vargas", "Vasquez", "Vazquez", "Vega", "Vela", "Velasco", "Velasquez", "Velazquez", "Velez", "Veliz",
    "Venegas", "Vera", "Verdugo", "Verduzco", "Vergara", "Viera", "Vigil", "Villa", "Villagomez", "Villalobos",
    "Villalpando", "Villanueva", "Villareal", "Villarreal", "Villaseñor", "Villegas", "Yañez", "Ybarra", "Yturrizaga",
    "Zabala", "Zambrano", "Zamora", "Zamudio", "Zapata", "Zaragoza", "Zarate", "Zavala", "Zayas", "Zelaya", "Zepeda",
    "Zuñiga"
];

const listaasignaturas = [
    "Matemáticas",
    "Lengua y Literatura",
    "Ciencias Naturales",
    "Ciencias Sociales",
    "Física",
    "Química",
    "Biología",
    "Historia",
    "Geografía",
    "Filosofía",
    "Educación Física",
    "Arte",
    "Música",
    "Tecnología",
    "Informática",
    "Inglés",
    "Francés",
    "Alemán",
    "Dibujo Técnico",
    "Religión",
    "Ética",
];